// <auto-generated />
using System;
using Atividade_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Atividade_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260916014331_AtividadeFKProfessores2")]
    partial class AtividadeFKProfessores2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Atividade_API.Models.Atividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DisciplinaID")
                        .HasColumnType("int");

                    b.Property<int?>("ProfessorID")
                        .HasColumnType("int");

                    b.Property<int?>("TurmaID")
                        .HasColumnType("int");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaID");

                    b.HasIndex("ProfessorID");

                    b.HasIndex("TurmaID");

                    b.ToTable("Atividade");
                });

            modelBuilder.Entity("Atividade_API.Models.Boletim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoID")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinaID")
                        .HasColumnType("int");

                    b.Property<float>("nota")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AlunoID");

                    b.HasIndex("DisciplinaID");

                    b.ToTable("Boletim");
                });

            modelBuilder.Entity("Atividade_API.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<int?>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<string>("nomeDisciplina")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Disciplina");
                });

            modelBuilder.Entity("Atividade_API.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hashSenha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idade")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoPessoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pessoa");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Pessoa");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Atividade_API.Models.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<int>("anoLetivo")
                        .HasColumnType("int");

                    b.Property<string>("nomeTurma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("turno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Turma");
                });

            modelBuilder.Entity("DisciplinaTurma", b =>
                {
                    b.Property<int>("DisciplinasId")
                        .HasColumnType("int");

                    b.Property<int>("TurmasId")
                        .HasColumnType("int");

                    b.HasKey("DisciplinasId", "TurmasId");

                    b.HasIndex("TurmasId");

                    b.ToTable("DisciplinaTurma");
                });

            modelBuilder.Entity("Atividade_API.Models.Usuarios.Administrador", b =>
                {
                    b.HasBaseType("Atividade_API.Models.Pessoa");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("Atividade_API.Models.Usuarios.Aluno", b =>
                {
                    b.HasBaseType("Atividade_API.Models.Pessoa");

                    b.Property<int?>("TurmaId")
                        .HasColumnType("int");

                    b.Property<int?>("TurmaId1")
                        .HasColumnType("int");

                    b.Property<int>("matricula")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("TurmaId");

                    b.HasIndex("TurmaId1");

                    b.HasDiscriminator().HasValue("Aluno");
                });

            modelBuilder.Entity("Atividade_API.Models.Usuarios.Professor", b =>
                {
                    b.HasBaseType("Atividade_API.Models.Pessoa");

                    b.Property<string>("cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("formacoes")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Professor");
                });

            modelBuilder.Entity("Atividade_API.Models.Atividade", b =>
                {
                    b.HasOne("Atividade_API.Models.Disciplina", "disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaID");

                    b.HasOne("Atividade_API.Models.Usuarios.Professor", "professor")
                        .WithMany()
                        .HasForeignKey("ProfessorID");

                    b.HasOne("Atividade_API.Models.Turma", "turma")
                        .WithMany()
                        .HasForeignKey("TurmaID");

                    b.Navigation("disciplina");

                    b.Navigation("professor");

                    b.Navigation("turma");
                });

            modelBuilder.Entity("Atividade_API.Models.Boletim", b =>
                {
                    b.HasOne("Atividade_API.Models.Usuarios.Aluno", "aluno")
                        .WithMany()
                        .HasForeignKey("AlunoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atividade_API.Models.Disciplina", "disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("aluno");

                    b.Navigation("disciplina");
                });

            modelBuilder.Entity("Atividade_API.Models.Disciplina", b =>
                {
                    b.HasOne("Atividade_API.Models.Usuarios.Professor", null)
                        .WithMany("Disciplinas")
                        .HasForeignKey("ProfessorId");
                });

            modelBuilder.Entity("Atividade_API.Models.Turma", b =>
                {
                    b.HasOne("Atividade_API.Models.Usuarios.Professor", null)
                        .WithMany("Turmas")
                        .HasForeignKey("ProfessorId");
                });

            modelBuilder.Entity("DisciplinaTurma", b =>
                {
                    b.HasOne("Atividade_API.Models.Disciplina", null)
                        .WithMany()
                        .HasForeignKey("DisciplinasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atividade_API.Models.Turma", null)
                        .WithMany()
                        .HasForeignKey("TurmasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Atividade_API.Models.Usuarios.Aluno", b =>
                {
                    b.HasOne("Atividade_API.Models.Turma", "turma")
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Atividade_API.Models.Turma", null)
                        .WithMany("Alunos")
                        .HasForeignKey("TurmaId1");

                    b.Navigation("turma");
                });

            modelBuilder.Entity("Atividade_API.Models.Turma", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("Atividade_API.Models.Usuarios.Professor", b =>
                {
                    b.Navigation("Disciplinas");

                    b.Navigation("Turmas");
                });
#pragma warning restore 612, 618
        }
    }
}
